### ISSUE TITLE
Add missing documentation

### ISSUE THREAD

**Issue by dgarijo** [TEC-Toolkit/tec-toolkit.github.io#5]
- [x] Running example for the ontologies (both ECFO and PECO)
- [x] Sample SPARQL queries for the ECFKG
- [x] How to download and operate with PECO traces (we have a query, but it's not clear where to perform it)
- [x] Running validation queries

**Comment by stefanogermano** [comment]
As I mentioned to Milan yesterday, I think we should discuss this because we have completely different opinions on this.

**Comment by dgarijo** [comment]
Closing as completed
